### PR TITLE
Make settings items look tappable

### LINKED ISSUE #1327: Settings items should look clickable
### Description:

Three buttons in settings: 'Report a bug', 'Privacy policy', 'Terms of use' don't look like they are actionable. Look at Apple's settings screen on the right. Actionable items have disclosure indicator or use global tint color to show that they can be tapped.
Cells without any of those looks like a regular label.

Report a bug should be colored, as it open a new tab in browser.
Privacy policy and terms of use should have disclosure indicator, they use push navigation to show next page.

zrzut ekranu 2017-11-20 o 17 57 54

### Steps to Reproduce

  1. Open settings

**Actual result:**

Cells don't look actionable.
**Expected result:**
Cells should look actionable.
**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

1.5 (17.11.07.17)
**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Liunkae**
Fixes #1327

Screenshot of new appearance:
EDIT: `Report a bug` has been converted to a caret like the other items.

### CODE REVIEW

**Comment by jhreis** [comment]
I like the `>`, not so sure about the coloring though, I think it calls it out too much. If you convert all actionable items to carets I will merge this in.

**Comment by Liunkae** [comment]
@jhreis Converted `Report a bug` to a caret.

**Comment by jhreis** [comment]
So please don't kill me, but talked with the product team, and they actually did like the coloring and no caret for clickable links (exactly what you did). Any possibility you'd be willing to switch it back? We have also updated the coloring (see 1.6 branch) used in that menu. 

Sorry about this 😬

**Comment by Liunkae** [comment]
@jhreis No problem! 😉 Changed back to what I originally had.

**Pull request merged**
