### PR TITLE
Update ISSUE_TEMPLATE to the new look on browser-laptop and updates the README 

### PR DESCRIPTION
**Pull request by Jacalz**
Not much more to it 👍 

Closes:  #1227

### CODE REVIEW

**Comment by srirambv** [comment]
Please log an issue and link the PR

**Comment by Jacalz** [comment]
Happy to help 👍

**Comment by jhreis** [comment]
I see this is already merged, but can @Jacalz please still address my question?

**Comment by jhreis** [comment]
I also, think the beta question is still important.

**Comment by srirambv** [comment]
Beta build question is still there. This is what the new layout looks like
image

**Comment by jhreis** [comment]
Was actually just talking with @Jacalz about this. Is that question still relevant due to having the Brave Version? We can pretty easily identify if something is beta or not ourselves with that info. Thoughts @srirambv ?

**Comment by srirambv** [comment]
No. We can exclude the beta version. But I'd suggest that we need to mention in template to provide full details including build number so that we don't have to ask when users report.

**Comment by Jacalz** [comment]
I have opened a new PR that has some more information and such but I am a bit on the side of keeping the beta and release channels to match with browser-android-tab because it is needed there as far as I know 😅

**Pull request merged**
