### PR TITLE
fix #1248 Add yahoo and bing to sv-SE

### LINKED ISSUE #1248: Add Bing and yahoo to Swedish search engines
## STR for QA to test
1. Set device region to Sweden
2. Go to settings > search engines and set bing as default search engine
3. Type "Frallor" in adress bar and hit search, ensure that it searched for "Frallor"
4. Go to settings > search engines and set yahoo as default search engine
5. type "Frallor" in adress bar and hit search, ensure that it searches for "Frallor"

### Description:

Bing and Yahoo are not avaliable if you have Swedish set to your region but some Swedes use these search engines, they are also available on browser-laptop 
### Steps to Reproduce

  1. Set device region to Sweden
  2. Go to settings > search engines 
  3. look for yahoo and bing, they are noty there

**Actual result:**

No bing and yahoo

**Expected result:**
Should show bing and yahoo

### PR DESCRIPTION
**Pull request by Jacalz**
closes #1248 
This adds yahoo and bing to search engines when using Sweden as region.

### CODE REVIEW

**Comment by Jacalz** [comment]
I have tested this and it works like it should :+1:

**Comment by Jacalz** [comment]
There is not an enormous amount of users using these in Sweden but it might be good for some people 👍

**Comment by jhreis** [comment]
Going to hold this until 1.6.

**Comment by Jacalz** [comment]
Sounds good, not very high priority since it doesn’t fix any bugs 😅

**Comment by kjozwiak** [comment]
As per the above conversation between @Jacalz and @jhreis , moving into the next milestone.

**Comment by Jacalz** [comment]
Awesome 👏

**Pull request merged**
