### PR TITLE
Fix #586, setting allowsInlineMediaPlayback to true changes behavior

### LINKED ISSUE #586: Video shows up in full screen after reopening the app
Description:
Video shows up in full screen after reopening the app

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should continue playing video in the tab only and not in fullscreen mode

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18

- Steps to reproduce:
    1. Open any video in YouTube
    2. Exit full screen but keep the video running
    3. Switch to a different tab
    4. Press home button to background the app
    5. Open the app again, Video comes in fullscreen

** Website problems only: Yes
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Verified on Dolphin & Puffin, Dolphin continues background play, Puffin pauses playback

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by ryan-liveware**

### CODE REVIEW

**Comment by garvankeeley** [comment]
Hi thanks for the PR! However, I am not sure how this will fix the case where the user wants full-screen video, but switching tabs produces the unexpected behaviour described in the report. 
How did this change the behaviour when you tried it?

**Comment by ryan-liveware** [comment]
Hi Garvan, You’re welcome! The behavior that I believed the issue was describing is that the video player comes in full-screen when backgrounding+foregrounding while playing a video in-line. I believe the PR will fix that behavior by keeping the player in-line when it plays after foregrounding. 

Also, I believe that the PR fixes the behavior where an in-line player, that’s playing when the tab is switched, switches to full-screen after switching back to the tab and pressing play again.

It was my assumption from the report that the user wants the player in-line and not full-screen after backgrounding+foregrounding according to the expected behavior. I am not sure about the case you are describing where the user wants full-screen. Please let me know if I am not understanding the description.

Thanks

**Comment by garvankeeley** [comment]
What affect does this have on the case where someone plays a video? I assume there is some way to make it full-screen? For instance, our app is a 'better' youtube viewer than the native app, because it behaves very similarly (full screen playback) with nearly all pre-roll ads blocked.
I am not familiar with how this setting will affect full-screen playback, maybe there is a way to tap on the video to then make it full-screen? That might be cool. I'll try a build with it on and see what it does. Thanks!

**Comment by ryan-liveware** [comment]
No affect, the video still plays in full-screen when the user first taps the video after the load, and the in-line video will still contain the full-screen button as well. I don’t believe the setting will affect full-screen playback negatively when it comes to ad blocking. The setting is set to true by default on the iPad and not on the iPhone which probably has something to do with smaller screen sizes. Also, Safari and Chrome appear to have the setting set to true on the iPhone after doing some comparison testing. You're welcome!

**Comment by garvankeeley** [comment]
Tried it out, lgtm so far, landing!

**Pull request merged**
