### PR TITLE
Fix #1409, done button bg color + sync screens layout improvements.

### LINKED ISSUE #1409: Sync setup screen Done button needs a new bg colour
### Description:
Sync setup screen Done button needs a new bg colour keeping it similar to the first screen of the sync setup

**Actual result:**
image
image

**Expected result:**
image
image

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
1.5.3(18.01.20.12)

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
It looks better on smaller devices like iPhone SE.
Also removed scroll view and used UIStackViews instead.

### CODE REVIEW

**Comment by jamesmudgett** [comment]
Will hold off on merging this one until we apply the same layout updates to other sync screens.

**Comment by iccub** [comment]
Just fyi, decided to do other layout fixes on the same PR, so if everything is good we can merge changes for all screens at once.

**Comment by jhreis** [comment]
@iccub to confirm, this PR is completed now, right?

**Comment by iccub** [comment]
@jhreis one screen left, the one with segmented control issues we've discussed yesterday, will notify you once it's finished

**Comment by jamesmudgett** [comment]
Looks good, two things:

1. On codewords screen we can reduce the horizontal spacing between the cells to allow for more room on longer keywords. 
2. The option (segment control) should be on a white background instead of the grey background.

**Comment by iccub** [comment]
This PR also contains improved codewords listing.

zrzut ekranu 2018-01-26 o 20 13 23

**Pull request merged**
